### PR TITLE
fix for Joomla 3.8 support

### PR DESCRIPTION
**Pull request by shandak**

### CODE REVIEW

**Review by jatitoam — COMMENTED** [review]
I can see new classes added that I think are unrelated to 3.8 right?  Or are they needed for this?
If they're new additions but not necessary for compatibility, can you please send it in a different PR?

**Comment by shandak** [comment]
The new classes are the way to compatibility with Joomla 3.8.
I asked Lu to check new package with our projects.
Please wait until he will confirm that the path is ok.

**Comment by jatitoam** [comment]
cc @luredweb

**Comment by lunguyenhat** [comment]
Hi @shandak I can override the model, controller class, but Helper class can't

**Comment by shandak** [comment]
@luredweb please check with the latest changes again. Thanks.

**Comment by arkadoo** [comment]
Hi.
Where I can find the last version with helpers solved issue? can you help me? thanks

**Comment by lunguyenhat** [comment]
Hi @arkadoo Please set plugin to the first position to solve helper issue

**Comment by shandak** [comment]
@jatitoam @Kixo these changes were checked by @luredweb and all works fine. I recommend to merge it.
But we still have an issue with redCORE loader compatibility here https://github.com/redCOMPONENT-COM/redCORE/pull/796 Please look at it when you have time. Thanks.

**Comment by shandak** [comment]
@Kixo please take a look at it. thanks

**Comment by Kixo** [comment]
why are you adding those library files in the overwrite folder? you will have to keep those files up to date like this, maybe add a checker if the files exist to not load them?

**Comment by shandak** [comment]
I added files which have to be overridden. Even if a file exists in the Joomla core - it has to be overridden with specific changes to have the ability use this plugin.

**Review by Kixo — APPROVED** [review]

**Pull request merged**
